---
title: "Assignment 3"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require(fivethirtyeight)) {install.packages('fivethirtyeight')}
library(fivethirtyeight)
```

For this assignment we are using a dataset from the website [Fivethirtyeight](http://fivethirtyeight.com/). All these datasets are available on their [GitHub page](https://github.com/fivethirtyeight/data/) and in the `fivethirtyeight` package.

1. Install and load the `fivethirtyeight` library. For this assigment we are using the dataset `bad_drivers`.

2. In the narrative, add a brief description (`?bad_drivers` for a description of the dataset) using *inline code* to show the variable names.

3. Plot a dot chart of premiums by losses. Map the count of drivers to the size of the dots.

4. Test what values from `state` are equal to "Louisiana" and assign the output to a new variable called `Louisiana' (logical)

5. Map the variable "Louisiana" to `color`. That way, the dot referring to Louisiana should have a different color.

6. In your narrative, use inline code to report the average insurance premium and count of losses in US, and the premium and losses in Louisiana. Do not type those values manually, but extract them from the dataset using inline code.

7. Report in a tabular format the 5 states with the highest premiums (include only state and insurance_premiums)

8. Reshape the dataset gathering together perc_speeding, perc_alcohol, perc_not_distracted in one variable, paired with their pecentages. Name this variable "ViolationType" and the variable for the value pairs "perc".

9. Use facetting (DO NOT use 3 distinct calls to `ggplot()`) to plot 3 dot plots for the correlation between:

   - insurance_premiums and perc_alcohol
   - insurance_premiums and perc_speeding
   - insurance_premiums and perc_not_distracted
   
   
10. Mute the code for both charts and add a title to both. Knit to html.
   
   



