---
title: "Terrorism in Europe"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
```

```{r}
dt <- read_csv(file = 'https://raw.githubusercontent.com/fivethirtyeight/data/master/terrorism/eu_terrorism_fatalities_by_country.csv')
dtYear <- tidyr::gather(dt, 'state', 'casualties', - iyear)

dt <- dtYear %>% 
  group_by(state) %>% summarise(total = sum(casualties))
```


Column {data-width=650}
-----------------------------------------------------------------------

### Europe

```{r}
dt %>% 
  ggplot(aes(x = state, y = total)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_col()
```

Column {data-width=350}
-----------------------------------------------------------------------

### State 1

```{r}
<<<<<<< HEAD
function.plot <- function(dt,myCountry){

dt <- dt %>% filter(state == myCountry)
 ggplot( data = dt,aes(iyear, casualties ))+
   scale_x_continuous("Year")+
   geom_line()
}
function.plot(dtYear,"United Kingdom")
=======
filter(dtYear, state == 'United Kingdom') %>% 
ggplot(aes(x = iyear, y = casualties)) +
  scale_x_continuous(name = 'year') + 
  geom_line()
>>>>>>> d25149dae5283c1c2dc30c804a64fd8cb0b93c8d
```

### State 2

```{r}
<<<<<<< HEAD
function.plot(dtYear,"Belgium")
=======
filter(dtYear, state == 'Belgium') %>% 
ggplot(aes(x = iyear, y = casualties)) +
  scale_x_continuous(name = 'year') +
  geom_line()
>>>>>>> d25149dae5283c1c2dc30c804a64fd8cb0b93c8d
```

