---
title: "Terrorism in Europe"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(plotly)
```

```{r}
dtYear <- read_csv(file = 'https://raw.githubusercontent.com/fivethirtyeight/data/master/terrorism/eu_terrorism_fatalities_by_country.csv') %>% 
  tidyr::gather('state', 'casualties', - iyear)
dt <- dtYear %>% 
  group_by(state) %>% summarise(total = sum(casualties))
```

Inputs {.sidebar}
-------------------------------------

```{r}
statesNames <- setNames(unique(dt$state), unique(dt$state)) %>% as.list()

#drop down menu for the 1st plot
 selectInput("state1", label = h4("State 1"), 
    choices = statesNames, 
    selected = 'United Kingdom')

#dropdown menu for the second (uncomment and fill the ...)
<<<<<<< HEAD
 selectInput('state2', label = h4("State 2"), 
    choices = statesNames, 
    selected = 'Belgium')
=======
selectInput("state2", label = h4("State 2"),
   choices = statesNames,
   selected = 'France')
>>>>>>> 5a48964e99032853b43fbf4a1519d91d9afa2189
```
 


Column {data-width=650}
-----------------------------------------------------------------------

### Europe

```{r}

renderPlot({
  #create a logical variable named `selected` that is TRUE if a country is selected in either one of the drop-down menus and FALSE otherwise. To extract the selected value use input$selectInputID e.g., input$state1
  dt %>%  mutate(selected  = input$state1 %in%  statesNames) %>% 
  ggplot(aes(x = state, y = total, fill = selected)) +
  geom_col(show.legend = F) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
})


```

Column {data-width=350}
-----------------------------------------------------------------------

### `r reactive({ input$state1 })`

```{r}
#create a function to plot a linechart given a dataset `df` and a country name `country`
function.statePlot <- function(dt,myCountry){
dt <- dt %>% filter(state == myCountry)
 ggplot( data = dt,aes(iyear, casualties ))+
   scale_x_continuous("Year")+
   geom_line()
}
function.statePlot(dtYear,input$state1)

renderPlot({
 dtYear %>% mutate(selected = input$state1 %in% statesNames) %>%
   ggplot(aes(x = iyear, y = casualties)) + geom_line()
})
```

### Make this reactive using reactive({})

```{r}

renderPlot({
 dtYear %>% mutate(selected = input$state2 %in% statesNames) %>%
   ggplot(aes(x = iyear, y = casualties)) + geom_line()
})
```

