---
title: "HW5"
author: "Tyler McDonald"
date: "November 9, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
source(here('lectures/lesson11_openData/tokenSocrata.R'))
library(RSocrata)
library(here)
library(tidyverse)
library(ggmap)
apiEndpoint <- 'https://data.brla.gov/resource/uqxt-dtpe.csv?'
apiEndpoint2 <- 'https://data.brla.gov/resource/4w4d-4es6.csv?'
apiEndpoint3 <- 'https://data.brla.gov/resource/5rji-ddnu.csv?'
query <- "$where=createdate between '2016-08-12' and '2016-08-22'"
dt_311 <- read.socrata(paste0(apiEndpoint, query), app_token = token[['app']])
dt_311 <- as_tibble(dt_311)
dt_311 <- dt_311 %>% 
  mutate(geolocation = str_extract_all(geolocation, '[-,.,0-9]+')) %>% 
  mutate(long = map_chr(geolocation, 1), lat = map_chr(geolocation, 2)) %>% 
  mutate_at(vars(long, lat), as.double)
query <- "$where=disp_date between '2016-08-12' and '2016-08-22'"
dt_fire <- read.socrata(paste0(apiEndpoint2, query), app_token = token[['app']])
dt_fire <- as_tibble(dt_fire)
dt_fire <- dt_fire %>% 
  filter(geolocation != "") %>%
  mutate(geolocation = str_extract_all(geolocation, '[-,.,0-9]+')) %>%
  mutate(long = as.double(map_chr(geolocation, 1)), lat = as.double(map_chr(geolocation, 2)))
query <- "$where=offense_date between '2016-08-12' and '2016-08-22'"
dt_911 <- read.socrata(paste0(apiEndpoint3, query), app_token = token[['app']])
dt_911 <- as_tibble(dt_911)
dt_911 <- dt_911 %>% 
  filter(geolocation != "") %>%
  mutate(geolocation = str_extract_all(geolocation, '[-,.,0-9]+')) %>%
  mutate(long = as.double(map_chr(geolocation, 1)), lat = as.double(map_chr(geolocation, 2)))
brMap <- readRDS(here::here('data/mapTerrainBR.RDS'))
ggmap::ggmap(brMap) +
  geom_point(data = filter(dt_311, parenttype == "DRAINAGE, EROSION, FLOODING OR HOLES"), aes(x = long, y = lat, ), color = 'darkgreen', alpha = .33) + geom_point(data = filter(dt_fire, inci_descript == "Severe weather or natural disaster, Other" | inci_descript == "Water evacuation"), aes(x = long, y = lat), color = 'darkred', alpha = .33) + geom_point(data = filter(dt_911, offense_desc == "LOOTING"), aes(x = long, y = lat), color = 'darkblue', alpha = .33) + ggtitle('Position of calls to 311, Fire Brigade, and 911') + scale_color_manual(name = "Calls", labels = c("DRAINAGE, EROSION, FLOODING OR HOLES", "Severe weather or natural disaster, Other or Water evacuation", "LOOTING"), values = colors)
  
```

